name: Get Latest Version Test

on:
  pull_request:
    paths:
      - .github/workflows/get_latest_version_test.yml
      - cmd/get-latest-version/**
      - go.mod
      - go.sum

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - name: Run integration test
        run: go test -tags=integration ./cmd/...
