name: Publish image

on:
  push:
    branches:
      - main
    paths:
      - "gcloud_sdk_version.txt"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - id: get_version
        name: Get version
        run: echo "version=$(cat ./gcloud_sdk_version.txt)" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: shirakiya/gcloud-sdk:latest,shirakiya/gcloud-sdk:${{ steps.get_version.outputs.version }}
